# Generated by Django 5.0 on 2025-09-15 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_review_liked_review_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
    ]
