# Generated by Django 5.0 on 2025-09-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
